apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orakel-webpage
  name: orakel-webpage
  namespace: orakel-of-funk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orakel-webpage
  strategy: {}
  template:
    metadata:
      labels:
        app: orakel-webpage
    spec:
      serviceAccountName: orakel-of-funk
      containers:
      - image: ghcr.io/peschmae/orakel-webpage:main
        name: orakel-webpage
        resources: 
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8000
          name: http
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orakel-webpage
  name: orakel-webpage
  namespace: orakel-of-funk-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: orakel-webpage
  type: ClusterIP
